"use client"

import { usePathname } from "next/navigation"

export default function Head() {
  const url = usePathname()?.split("/").reverse()[0] || "";
  let route = url.charAt(0)?.toUpperCase() + url?.slice(1);

  const modifier = route !== "" ? ` | ${route}` : ""; 

  return (
    <>
      <title>{'Digital Sky Studios' + modifier}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="assets/DSSLogo.ico" />
    </>
  )
}
